### ISSUE TITLE
add, remove and view favorites

### ISSUE THREAD

**Issue by Lugdu84** [Lugdu84/eatbetter#49]

**Comment by Lugdu84** [comment]
an user can add favorite farm
an user can remove favorite farm
an user can view these favorites farms

**Comment by JulieMB1706** [comment]
23/03: 
1. Front à finir
- récupérer design cards Floriane
- récupérer design coeur Floriane
2.Back 
- Fixer problème JS ( à check si toujours d'actu après le pull du 23/03 matin)
